### ISSUE TITLE
Ruley Panics

### ISSUE THREAD

**Issue by purespeech** [fiatjaf/relay29#1]
I'm getting this panic and haven't been able to figure it out yet

I have tried to create 9002 Group and some group users. I'm missing something. This is the debug console (sorry, it's not perhaps all that helpful but best I can get at this point):

```
DAP server listening at: 127.0.0.1:42067
Type 'dlv help' for list of commands.
10:25PM DBG initialized database path=./db
10:25PM INF running on http://0.0.0.0:5577
[khatru-relay] 2023/11/12 22:25:45 unexpected close error from : websocket: close 1000 (normal)
panic: panic called with nil argument

goroutine 24 [running]:
github.com/fiatjaf/eventstore/lmdb.(*LMDBBackend).QueryEvents.func1.1.1(0x0, {0x0, {0xc0000144d8, 0x1, 0x1}, {0xc0000144e0, 0x5, 0x8}, 0xc0000285a0, 0x0})
	/home/brian/go/pkg/mod/github.com/fiatjaf/eventstore@v0.2.8/lmdb/query.go:96 +0xe5c
created by github.com/fiatjaf/eventstore/lmdb.(*LMDBBackend).QueryEvents.func1.1 in goroutine 23
	/home/brian/go/pkg/mod/github.com/fiatjaf/eventstore@v0.2.8/lmdb/query.go:42 +0x4bb
Process 24926 has exited with status 2
Detaching
```

**Comment by fiatjaf** [comment]
Why are you running this? This is not meant to be used yet.

But thank you for the report, it may be helpful.

**Comment by purespeech** [comment]
It's a great concept with elegant code. Seems like a truly nice example of customization / application opportunities for Nostr. I was running it in advance of a small, local group of tech folks later this week. I wanted to see if I could get it operational enough from reading the code. I wrote some test Typescript in an effort to bootstrap/publish data for a concept demo. Thanks for putting it out there and sharing the code.

**Comment by fiatjaf** [comment]
I think the issue is that it is using an old version of `eventstore`. Locally I'm developing with the `eventstore` dependency tagged to `master` (as well as `khatru`).

I'll see if I can publish a better working version today.

**Comment by purespeech** [comment]
TYVM - I'll look more closely at the version tagging and will definitely work with it again at the next repo update.

**Comment by fiatjaf** [comment]
I think it should run more or less now.
